name: 'Savant Smart Contract Analyzer'
description: 'Analyzes changes in Solidity contracts between commits and creates an audit request in Savant.Chat'
branding:
  icon: 'search'
  color: 'blue'
inputs:
  base_commit:
    description: 'Base commit SHA for comparison'
    required: true
  head_commit:
    description: 'Head commit SHA for comparison'
    required: true
  github_token:
    description: 'GitHub token for repository access'
    required: false
    default: ${{ github.token }}
  api_token:
    description: 'API token for the audit service. Get it from https://savant.chat (Profile -> Settings -> API Keys)'
    required: true
  api_url:
    description: 'URL for the audit service API endpoint'
    required: false
    default: 'https://savant.chat/api/v1/ci-cd/requests'
  dry_run:
    description: 'Whether to perform a dry run (do not create real audit)'
    required: false
    default: 'false'
  tier:
    description: 'Tier'
    required: false
    default: 'advanced'
  notification_contacts:
    description: 'Comma-separated list of notification contacts (emails and Telegram usernames)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Send request to Savant.Chat
      shell: bash
      run: |
        echo "Sending request to Savant.Chat at ${{ inputs.api_url }}"
        echo "Inputs:"
        echo "  repo: ${{ github.repository }}"
        echo "  base_commit: ${{ inputs.base_commit }}"
        echo "  head_commit: ${{ inputs.head_commit }}"
        echo "  dry_run: ${{ inputs.dry_run }}"
        echo "  tier: ${{ inputs.tier }}"
        echo "  notification_contacts: ${{ inputs.notification_contacts }}"
        
        # Convert comma-separated notification_contacts to JSON array
        if [ -n "${{ inputs.notification_contacts }}" ]; then
          NOTIFICATION_CONTACTS_JSON=$(echo "${{ inputs.notification_contacts }}" | sed 's/[[:space:]]*,[[:space:]]*/","/g' | sed 's/^/"/' | sed 's/$/"/' | sed 's/^/[/' | sed 's/$/]/')
        else
          NOTIFICATION_CONTACTS_JSON="[]"
        fi
        echo "  notification_contacts_json: $NOTIFICATION_CONTACTS_JSON"
        
        PAYLOAD="{\"repo\":\"${{ github.repository }}\",\"base_commit\":\"${{ inputs.base_commit }}\",\"head_commit\":\"${{ inputs.head_commit }}\",\"github_token\":\"${{ inputs.github_token }}\",\"api_token\":\"${{ inputs.api_token }}\",\"dry_run\":${{ inputs.dry_run }},\"tier\":\"${{ inputs.tier }}\",\"notification_contacts\":$NOTIFICATION_CONTACTS_JSON}"
        echo "Request payload: $PAYLOAD"
        RESPONSE=$(curl -sS -X POST "${{ inputs.api_url }}" \
          -H "Authorization: Bearer ${{ inputs.api_token }}" \
          -H "Content-Type: application/json" \
          -d "$PAYLOAD") || true
        echo "Response body:"
        echo "$RESPONSE" | jq '(.requestLink, .requestId) |= "***"'
        # Try parsing JSON response
        if echo "$RESPONSE" | jq . >/dev/null 2>&1; then
          # Check if response contains an error
          ERROR_MSG=$(echo "$RESPONSE" | jq -r '.error // empty')
          if [ -n "$ERROR_MSG" ]; then
            echo "Error from API: $ERROR_MSG"
            ERROR_DETAILS=$(echo "$RESPONSE" | jq -r '.details // empty')
            if [ -n "$ERROR_DETAILS" ]; then
              echo "Details: $ERROR_DETAILS"
            fi
            exit 1
          fi
          AUDIT_URL=$(echo "$RESPONSE" | jq -r .requestLink)
        else
          echo "Non-JSON response (likely HTML). See above."
          exit 1
        fi
        # Ensure requestLink is present
        if [ -z "$AUDIT_URL" ] || [ "$AUDIT_URL" = "null" ]; then
          echo "Error: requestLink not found in JSON response"
          exit 1
        fi
        # Generate redirect HTML
        echo "<html><head><meta http-equiv=\"refresh\" content=\"0; URL=$AUDIT_URL\" /></head></html>" > audit.html
    - name: Upload audit redirect HTML
      uses: actions/upload-artifact@v4
      with:
        name: audit-redirect
        path: audit.html
